from typing import TYPE_CHECKING, Any

#from .locations import CRLocation
from worlds.generic.Rules import add_rule

if TYPE_CHECKING:
    from . import CRWorld

# Assign rules to CR items
def set_rules(world: "CRWorld"):
    for location_name, rule in get_rules_dict(world).items():
        add_rule(world.multiworld.get_location(location_name, world.player), rule)

# Define rules for CR
def get_rules_dict(world: "CRWorld") -> dict[str, Any]:
    player = world.player
    rules = {}

    rules.update({
        "Use Ray 01": lambda state: state.has("Ray 01", player),
        "Use Splendor": lambda state: state.has("Splendor", player),
        "Use Glory": lambda state: state.has("Glory", player),
        "Use Milky Way": lambda state: state.has("Milky Way", player),
        "Use Earth": lambda state: state.has("Earth", player),
        "Use Sol": lambda state: state.has("Sol", player),
        "Use Metal Ape": lambda state: state.has("Metal Ape", player),
        "Use Metal Bear": lambda state: state.has("Metal Bear", player),
        "Use Metal Ox": lambda state: state.has("Metal Ox", player),
        "Use Swift": lambda state: state.has("Swift", player),
        "Use Shrike": lambda state: state.has("Shrike", player),
        "Use Peregrine": lambda state: state.has("Peregrine", player),
        "Use Javelin": lambda state: state.has("Javelin", player),
        "Use Glaive": lambda state: state.has("Glaive", player),
        "Use Halberd": lambda state: state.has("Halberd", player),
        "Use Criminal": lambda state: state.has("Criminal", player),
        "Use Buggy": lambda state: state.has("Buggy", player),
        "Use Juggler": lambda state: state.has("Juggler", player),
        "Use Defender": lambda state: state.has("Defender", player),
        "Use Seeker": lambda state: state.has("Seeker", player),
        "Use Breaker": lambda state: state.has("Breaker", player),
        "Use Seal Head": lambda state: state.has("Seal Head", player),
        "Use Dour Head": lambda state: state.has("Dour Head", player),
        "Use Tank Head": lambda state: state.has("Tank Head", player),
        "Use Ray Legend": lambda state: state.has("Ray Legend", player),
        "Use Oil Can": lambda state: state.has("Oil Can", player),
        "Use Ray Warrior": lambda state: state.has("Ray Warrior", player),
        "Use Rakansen": lambda state: state.has("Rakansen", player),
        "Use Ruhiel": lambda state: state.has("Ruhiel", player),
        "Use Athena": lambda state: state.has("Athena", player),
        "Use Chickenheart": lambda state: state.has("Chickenheart", player),
        "Use Basic Gun": lambda state: state.has("Basic Gun", player),
        "Use 3-Way Gun": lambda state: state.has("3-Way Gun", player),
        "Use Gatling Gun": lambda state: state.has("Gatling Gun", player),
        "Use Vertical Gun": lambda state: state.has("Vertical Gun", player),
        "Use Sniper Gun": lambda state: state.has("Sniper Gun", player),
        "Use Stun Gun": lambda state: state.has("Stun Gun", player),
        "Use Hornet Gun": lambda state: state.has("Hornet Gun", player),
        "Use Flame Gun": lambda state: state.has("Flame Gun", player),
        "Use Dragon Gun": lambda state: state.has("Dragon Gun", player),
        "Use Splash Gun": lambda state: state.has("Splash Gun", player),
        "Use Left Arc Gun": lambda state: state.has("Left Arc Gun", player),
        "Use Right Arc Gun": lambda state: state.has("Right Arc Gun", player),
        "Use Shotgun Gun": lambda state: state.has("Shotgun Gun", player),
        "Use Rayfall Gun": lambda state: state.has("Rayfall Gun", player),
        "Use Bubble Gun": lambda state: state.has("Bubble Gun", player),
        "Use Eagle Gun": lambda state: state.has("Eagle Gun", player),
        "Use V Laser Gun": lambda state: state.has("V Laser Gun", player),
        "Use Magnum Gun": lambda state: state.has("Magnum Gun", player),
        "Use Needle Gun": lambda state: state.has("Needle Gun", player),
        "Use Starshot Gun": lambda state: state.has("Starshot Gun", player),
        "Use Glider Gun": lambda state: state.has("Glider Gun", player),
        "Use Homing Star Gun": lambda state: state.has("Homing Star Gun", player),
        "Use Trap Gun": lambda state: state.has("Trap Gun", player),
        "Use Drill Gun": lambda state: state.has("Drill Gun", player),
        "Use Titan Gun": lambda state: state.has("Titan Gun", player),
        "Use Claw Gun": lambda state: state.has("Claw Gun", player),
        "Use Knuckle Gun": lambda state: state.has("Knuckle Gun", player),
        "Use Afterburner Gun": lambda state: state.has("Afterburner Gun", player),
        "Use Blade Gun": lambda state: state.has("Blade Gun", player),
        "Use Meteor Storm Gun": lambda state: state.has("Meteor Storm Gun", player),
        "Use Twin Fang Gun": lambda state: state.has("Twin Fang Gun", player),
        "Use Gravity Gun": lambda state: state.has("Gravity Gun", player),
        "Use Phoenix Gun": lambda state: state.has("Phoenix Gun", player),
        "Use Can Gun": lambda state: state.has("Can Gun", player),
        "Use Left Pulse Gun": lambda state: state.has("Left Pulse Gun", player),
        "Use Right Pulse Gun": lambda state: state.has("Right Pulse Gun", player),
        "Use Sword Storm Gun": lambda state: state.has("Sword Storm Gun", player),
        "Use Ion Gun": lambda state: state.has("Ion Gun", player),
        "Use Flare Gun": lambda state: state.has("Flare Gun", player),
        "Use Left 5-Way Gun": lambda state: state.has("Left 5-Way Gun", player),
        "Use Right 5-Way Gun": lambda state: state.has("Right 5-Way Gun", player),
        "Use Halo Gun": lambda state: state.has("Halo Gun", player),
        "Use Wave Laser Gun": lambda state: state.has("Wave Laser Gun", player),
        "Use X Laser Gun": lambda state: state.has("X Laser Gun", player),
        "Use Crystal Strike Gun": lambda state: state.has("Crystal Strike Gun", player),
        "Use Wyrm Gun": lambda state: state.has("Wyrm Gun", player),
        "Use Raptor Gun": lambda state: state.has("Raptor Gun", player),
        "Use Waxing Arc Gun": lambda state: state.has("Waxing Arc Gun", player),
        "Use Waning Arc Gun": lambda state: state.has("Waning Arc Gun", player),
        "Use Standard Bomb": lambda state: state.has("Standard Bomb", player),
        "Use Standard F Bomb": lambda state: state.has("Standard F Bomb", player),
        "Use Standard S Bomb": lambda state: state.has("Standard S Bomb", player),
        "Use Wave Bomb": lambda state: state.has("Wave Bomb", player),
        "Use Straight G Bomb": lambda state: state.has("Straight G Bomb", player),
        "Use Straight S Bomb": lambda state: state.has("Straight S Bomb", player),
        "Use Straight T Bomb": lambda state: state.has("Straight T Bomb", player),
        "Use Right Flank H Bomb": lambda state: state.has("Right Flank H Bomb", player),
        "Use Left Flank H Bomb": lambda state: state.has("Left Flank H Bomb", player),
        "Use Right Wave Bomb": lambda state: state.has("Right Wave Bomb", player),
        "Use Left Wave Bomb": lambda state: state.has("Left Wave Bomb", player),
        "Use Burrow D Bomb": lambda state: state.has("Burrow D Bomb", player),
        "Use Burrow P Bomb": lambda state: state.has("Burrow P Bomb", player),
        "Use Freeze Bomb": lambda state: state.has("Freeze Bomb", player),
        "Use Tomahawk B Bomb": lambda state: state.has("Tomahawk B Bomb", player),
        "Use Tomahawk G Bomb": lambda state: state.has("Tomahawk G Bomb", player),
        "Use Gemini B Bomb": lambda state: state.has("Gemini B Bomb", player),
        "Use Gemini P Bomb": lambda state: state.has("Gemini P Bomb", player),
        "Use Submarine D Bomb": lambda state: state.has("Submarine D Bomb", player),
        "Use Submarine P Bomb": lambda state: state.has("Submarine P Bomb", player),
        "Use Crescent P Bomb": lambda state: state.has("Crescent P Bomb", player),
        "Use Crescent C Bomb": lambda state: state.has("Crescent C Bomb", player),
        "Use Dual Bomb": lambda state: state.has("Dual Bomb", player),
        "Use Dual C Bomb": lambda state: state.has("Dual C Bomb", player),
        "Use Acrobat Bomb": lambda state: state.has("Acrobat Bomb", player),
        "Use Delta Bomb": lambda state: state.has("Delta Bomb", player),
        "Use Wall Bomb": lambda state: state.has("Wall Bomb", player),
        "Use Smash Bomb": lambda state: state.has("Smash Bomb", player),
        "Use Double Mine Bomb": lambda state: state.has("Double Mine Bomb", player),
        "Use Geo Trap Bomb": lambda state: state.has("Geo Trap Bomb", player),
        "Use Titan Bomb": lambda state: state.has("Titan Bomb", player),
        "Use Can Bomb": lambda state: state.has("Can Bomb", player),
        "Use Standard K Bomb": lambda state: state.has("Standard K Bomb", player),
        "Use Submarine K Bomb": lambda state: state.has("Submarine K Bomb", player),
        "Use Crescent K Bomb": lambda state: state.has("Crescent K Bomb", player),
        "Use Standard X Bomb": lambda state: state.has("Standard X Bomb", player),
        "Use Treble Bomb": lambda state: state.has("Treble Bomb", player),
        "Use Wyvern Bomb": lambda state: state.has("Wyvern Bomb", player),
        "Use Waxing Arc Bomb": lambda state: state.has("Waxing Arc Bomb", player),
        "Use Waning Arc Bomb": lambda state: state.has("Waning Arc Bomb", player),
        "Use Standard Pod": lambda state: state.has("Standard Pod", player),
        "Use Seeker F Pod": lambda state: state.has("Seeker F Pod", player),
        "Use Seeker G Pod": lambda state: state.has("Seeker G Pod", player),
        "Use Speed D Pod": lambda state: state.has("Speed D Pod", player),
        "Use Speed P Pod": lambda state: state.has("Speed P Pod", player),
        "Use Cockroach G Pod": lambda state: state.has("Cockroach G Pod", player),
        "Use Cockroach H Pod": lambda state: state.has("Cockroach H Pod", player),
        "Use Dolphin Pod": lambda state: state.has("Dolphin Pod", player),
        "Use Dolphin G Pod": lambda state: state.has("Dolphin G Pod", player),
        "Use Spider Pod": lambda state: state.has("Spider Pod", player),
        "Use Spider G Pod": lambda state: state.has("Spider G Pod", player),
        "Use Sky Freeze Pod": lambda state: state.has("Sky Freeze Pod", player),
        "Use Ground Freeze Pod": lambda state: state.has("Ground Freeze Pod", player),
        "Use Feint F Pod": lambda state: state.has("Feint F Pod", player),
        "Use Feint G Pod": lambda state: state.has("Feint G Pod", player),
        "Use Float F Pod": lambda state: state.has("Float F Pod", player),
        "Use Jumping B Pod": lambda state: state.has("Jumping B Pod", player),
        "Use Jumping G Pod": lambda state: state.has("Jumping G Pod", player),
        "Use Diving Pod": lambda state: state.has("Diving Pod", player),
        "Use Wave Pod": lambda state: state.has("Wave Pod", player),
        "Use Satellite Pod": lambda state: state.has("Satellite Pod", player),
        "Use Satellite H Pod": lambda state: state.has("Satellite H Pod", player),
        "Use Beast F Pod": lambda state: state.has("Beast F Pod", player),
        "Use Trio H Pod": lambda state: state.has("Trio H Pod", player),
        "Use Wall Pod": lambda state: state.has("Wall Pod", player),
        "Use Reflection Pod": lambda state: state.has("Reflection Pod", player),
        "Use Caboose C Pod": lambda state: state.has("Caboose C Pod", player),
        "Use Caboose T Pod": lambda state: state.has("Caboose T Pod", player),
        "Use Twin Flank F Pod": lambda state: state.has("Twin Flank F Pod", player),
        "Use Twin Flank G Pod": lambda state: state.has("Twin Flank G Pod", player),
        "Use Umbrella Pod": lambda state: state.has("Umbrella Pod", player),
        "Use Throwing D Pod": lambda state: state.has("Throwing D Pod", player),
        "Use Throwing P Pod": lambda state: state.has("Throwing P Pod", player),
        "Use Double Wave Pod": lambda state: state.has("Double Wave Pod", player),
        "Use Titan Pod": lambda state: state.has("Titan Pod", player),
        "Use Can Pod": lambda state: state.has("Can Pod", player),
        "Use Standard F Pod": lambda state: state.has("Standard F Pod", player),
        "Use Caboose X Pod": lambda state: state.has("Caboose X Pod", player),
        "Use Cheetah Pod": lambda state: state.has("Cheetah Pod", player),
        "Use Wolf Spider Pod": lambda state: state.has("Wolf Spider Pod", player),
        "Use Orca Pod": lambda state: state.has("Orca Pod", player),
        "Use Standard Legs": lambda state: state.has("Standard Legs", player),
        "Use High Jump Legs": lambda state: state.has("High Jump Legs", player),
        "Use Ground Legs": lambda state: state.has("Ground Legs", player),
        "Use Formula Legs": lambda state: state.has("Formula Legs", player),
        "Use Stabilizer Legs": lambda state: state.has("Stabilizer Legs", player),
        "Use Short Thrust Legs": lambda state: state.has("Short Thrust Legs", player),
        "Use Long Thrust Legs": lambda state: state.has("Long Thrust Legs", player),
        "Use Quick Jump Legs": lambda state: state.has("Quick Jump Legs", player),
        "Use Feather Legs": lambda state: state.has("Feather Legs", player),
        "Use Wide Jump Legs": lambda state: state.has("Wide Jump Legs", player),
        "Use Can Legs": lambda state: state.has("Can Legs", player),
        "Use Booster Legs": lambda state: state.has("Booster Legs", player),
        "Use Swallow Legs": lambda state: state.has("Swallow Legs", player),
        "Use Raven Legs": lambda state: state.has("Raven Legs", player),
        "Use Eclipse Legs": lambda state: state.has("Eclipse Legs", player),
        "Use Rahu I": lambda state: state.has("Rahu Evolution", player, 1),
        "Use Penumbra I Pod": lambda state: state.has("Rahu Evolution", player, 2),
        "Use Rahu I Gun": lambda state: state.has("Rahu Evolution", player, 3),
        "Use Rahu II": lambda state: state.has("Rahu Evolution", player, 4),
        "Use Penumbra II Pod": lambda state: state.has("Rahu Evolution", player, 5),
        "Use Rahu II Gun": lambda state: state.has("Rahu Evolution", player, 6),
        "Use Grand Cross Bomb": lambda state: state.has("Rahu Evolution", player, 7),
        "Use Ultimate Legs": lambda state: state.has("Rahu Evolution", player, 8),
        "Use Penumbra III Pod": lambda state: state.has("Rahu Evolution", player, 9),
        "Use Rahu III Gun": lambda state: state.has("Rahu Evolution", player, 10),
        "Use Rahu III": lambda state: state.has("Rahu Evolution", player, 11),
    })

    return rules